export default ubit = [{
    kljuc: "8",
    ime: "Manny Pacquiao",
    sport: "Boks",
    placeno: "0",
    nacin: "grupni",
    kratkiOpis:"Filipino politician and former professional boxer.[6] Nicknamed PacMan, he is regarded as one of the greatest professional boxers of all time.[7][8] He previously served as a Senator of the Philippines from 2016 to 2022.",
    duziOpis:"Pacquiao is the only eight-division world champion in the history of boxing and has won twelve major world titles.[9][10] He was the first boxer to win the lineal championship in five different weight classes,[11][12][13] the first boxer to win major world titles in four of the eight glamour divisions (flyweight, featherweight, lightweight, and welterweight),[14][15][16] and is the only boxer to hold world championships across four decades (1990s, 2000s, 2010s, and 2020s).[17] In July 2019, Pacquiao became the oldest welterweight world champion in history at the age of 40,[18] and the first boxer in history to become a recognized four-time welterweight champion after defeating Keith Thurman to win the WBA (Super) welterweight title.",
    lokacija:"Rijeka",
    

    },{
    kljuc: "2",
    ime: "Darin Matkovic",
    sport: "Nogomet",
    placeno: "1",
    nacin: "grupni",
    kratkiOpis:"Primarno sam na Hvaru, ali svratim i u Split.",
    duziOpis:"Vodim treninge na Hvaru, a ponekad i u Splitu. Trenutno sam u gipsu pa ništa ne pokazujem (samo se derem). Trening počinje uvijek na vrijeme i ne čeka se nikoga. Za ozljede ne odgovaram. Ako balun pobigne u more imamo rezervnu i brodicu da skupimo odbjeglu. Za Ujevićevu agresivnu igru ne odgovaram!!!",
    lokacija:"Hvar",
    },{
        kljuc: "5",
        ime: "Arnold Schwarzenegger",
        sport: "BodyBuilding",
        placeno: "0",
        nacin: "grupni",
        kratkiOpis:"Arnold Alois Schwarzenegger (born July 30, 1947) is an Austrian and American actor, businessman, filmmaker, politician, and retired professional bodybuilder best known for his roles in high-profile action movies. He served as the 38th governor of California from 2003 to 2011 and was among Time magazine's 100 most influential people in the world in 2004 and 2007.",
        duziOpis:"Schwarzenegger began lifting weights aged 15 and won the Mr. Universe title aged 20, and subsequently the Mr. Olympia title seven times. He is widely regarded as one of the greatest bodybuilders of all time,[7][8] and has written many books and articles about it.[9] The Arnold Sports Festival, considered the second-most important bodybuilding event after Mr. Olympia, is named after him.[10] He appeared in the bodybuilding documentary Pumping Iron (1977). He retired from bodybuilding and gained worldwide fame as a Hollywood action star, with his breakthrough in the sword and sorcery epic Conan the Barbarian (1982),[11] a box-office hit with a sequel in 1984.[12] After playing the title character in the science fiction film The Terminator (1984), he starred in Terminator 2: Judgment Day (1991) and three other sequels. His other successful action films included Commando (1985), The Running Man (1987), Predator (1987), Total Recall (1990), and True Lies (1994), in addition to comedy films such as Twins (1988), Kindergarten Cop (1990) and Jingle All the Way (1996).[13] He is the founder of the film production company Oak Productions.",
        lokacija:"Split",
        },{
        kljuc: "4",
        ime: "Zlatan Ibrahimovic",
        sport: "Nogomet",
        placeno: "0",
        nacin: "grupni",
        kratkiOpis:"Zlatan Ibrahimović rođen je u Švedskoj i sin je Bošnjaka Šefika Ibrahimovića podrijetlom iz područja Bijeljine i Hrvatice Jurke Gravić iz naselja Prkos u općini Škabrnja.[1] Otac Šefik emigrirao je u Švedsku 1977. godine gdje je sreo Jurku, koja je isto emigrirala u Švedsku.",
        duziOpis:"Počeo je igrati nogomet u dobi od šest godina, igrajući naizmjenično za juniorske klubove Malmö BI i FBK Balkan.[2][3] Potvrdio je u jednom intervjuu kako je, kada je njegov klub FBK Balkan gubio s 4:0 na poluvremenu, ušao kao zamjena i postigao 8 pogodaka. Kao mladi tinejdžer postao je stalni igrač za svoju gradsku momčad Malmö FF.[3] U dobi od 15 godina, Ibrahimović je želio okončati nogometnu karijeru kako bi radio na dokovima Malmöa, ali ga je njegov trener nagovorio neka nastavi igrati.[4] Ibrahimović je uspješno završio osnovnu školu. Bio je primljen u srednju školu Malmö Borgarskola, i iako je imao prosječne ocjene, uskoro ju je napustio kako bi se posvetio svojoj nogometnoj karijeri.",
        lokacija:"Zadar",
        
        
        },{
            kljuc: "3",
            ime: "Goran Caljkusic",
            sport: "Plivanje",
            placeno: "1",
            nacin: "grupni",
            kratkiOpis:"Laganica muzika i bučkanje u bazenu.",
            duziOpis:"Nudim trening za tjelo i dušu. Znači samo opušteno plivanje i dobra atmosfera. Morate nosit svoj kupaći, šugaman i presvlaku. Nema pušenja u bazenu i ako kasnite nije priša. Kad dođete dođete.",
            lokacija:"Split",
        },
        {
            kljuc: "6",
            ime: "Chris Bumstead",
            sport: "BodyBuilding",
            placeno: "0",
            nacin: "grupni",
            kratkiOpis:"Christopher Adam Bumstead (born 2 February 1995) is a Canadian IFBB professional bodybuilder. Bumstead is the reigning Mr. Olympia Classic Physique winner, having won the competition in 2019, 2020, 2021 and 2022. He was also the runner-up in 2017 and 2018.",
            duziOpis:"Growing up, bodybuilding was only a hobby for Bumstead.[7] He played many sports, ranging from soccer to baseball, basketball, and ice hockey. This developed Bumstead's interest in athletics, and he began weightlifting during his freshman year of high school. His sister's boyfriend, Iain Valliere, saw Bumstead's potential and helped him prepare to compete. As his bodybuilding goals began to stack up, All of a sudden, I was coming second at the Olympia,” he stated[citation needed]. Bumstead's first bodybuilding show was a regional level show in Ontario, which he participated in with his sister, Melissa Valliere. They both won the overall, with Bumstead winning as a junior. He found himself in love with the sport of bodybuilding after his first show. He started to work with Iain first hand and devoted his life to the sport.",
            lokacija:"Rijeka",
            },{
                kljuc: "7",
                ime: "Mike Tyson",
                sport: "Boks",
                placeno: "0",
                nacin: "individualni",
                kratkiOpis:"American former professional boxer who competed from 1985 to 2005. Nicknamed Iron Mike[4] and Kid Dynamite in his early career, and later known as The Baddest Man on the Planet,[5] Tyson is considered to be one of the greatest heavyweight boxers of all time.",
                duziOpis:"In 1992, Tyson was convicted of rape and sentenced to six years in prison, although he was released on parole after three years.[10][11][12] After his release in 1995, he engaged in a series of comeback fights, regaining the WBA and WBC titles in 1996 to join Floyd Patterson, Muhammad Ali, Tim Witherspoon, Evander Holyfield and George Foreman as the only men in boxing history to have regained a heavyweight championship after losing it. After being stripped of the WBC title in the same year, Tyson lost the WBA title to Evander Holyfield by an eleventh round stoppage. Their 1997 rematch ended when Tyson was disqualified for biting Holyfield's ears, one bite notoriously being strong enough to remove a portion of his right ear. In 2002, Tyson fought for the world heavyweight title, losing by knockout to Lennox Lewis.",
                lokacija:"Zadar",
            },
                {
                    kljuc: "1",
                    ime: "Ante Vrkic",
                    sport: "Kickbox",
                    placeno: "1",
                    nacin: "grupni",
                    kratkiOpis:"Treninzi samoobrane za sve uzraste.",
                    duziOpis:"Držim trening za rekreativce i borce. Ne mogu trčat, al mogu pametovat. Trening nikad ne počinje na vrijeme već 20 do 30 minuta kasnije. Potrebno je imati svoje zubalo i bandaže, a rukavice imate i u klubu.",
                    lokacija:"Zadar",
                    },
                {
                    kljuc: "9",
                    ime: "Boban Marjanović",
                    sport: "Košarka",
                    placeno: "0",
                    nacin: "grupni",
                    kratkiOpis:"Serbian professional basketball player for the Houston Rockets of the National Basketball Association (NBA). He also plays for the Serbian national basketball team in international competitions.",
                    duziOpis:"Marjanović signed a one-year, $1.2 million contract with the San Antonio Spurs.[28][29] He made his NBA debut on October 30, recording six points and five rebounds in the Spurs' 102–75 win over the Brooklyn Nets.[30] On December 4, he was assigned to the Austin Spurs, San Antonio's D-League affiliate.[31] He was recalled by San Antonio on December 6,[32] and, the following day, scored 18 points on 8-of-10 shooting in a 119–68 win over the Philadelphia 76ers.[33] On December 28, in a win over the Minnesota Timberwolves, with Tim Duncan out injured and LaMarcus Aldridge limited to six points, Marjanović scored 17 points on 7-of-7 shooting in 14 minutes to help the Spurs defeat the Timberwolves 101–95 and extend their franchise-record home winning streak to 27 games (dating to 2014–15 season).",
                    lokacija:"Split",
                    },{
                    kljuc: "10",
                    ime: "Mirko Filipović",
                    sport: "Kickbox",
                    placeno: "0",
                    nacin: "grupni",
                    kratkiOpis:"bivši borac mješovitih borilačkih vještina, hrvatski boksač, kickboksač, K-1 borac, bivši političar i specijalac Antiterorističke jedinice Lučko.",
                    duziOpis:"21-godišnji Mirko Filipović nastupio je na K-1 Grand Prix turniru. Prvo je pobijedio prošlogodišnjeg finalista, Jerome Le Bannera, no zatim biva poražen od poznatog Ernesta Hoosta. Ponovno se vratio za 3 godine porazivši Britanca Ricky  Nicholsona, no onda je izgubio od švicarca Xhavit Bajramija. Poslije toga dobiva pozivnicu za međunarodni turnir gdje je iznenadio cijeli svijet porazivši K-1 borca Mikea Bernarda u jednoj od ponajboljih K-1 borbi dotad. Nakon Bernarda, Mirko je porazio i japansku zvijezdu Musashija te australskog karate borca Sam Greca, dok ga iste večeri nije opet porazio Ernesto Hoost. Jedan od uzroka tog poraza je slomljeno rebro iz prijašnjih borbi.",
                    lokacija:"Zagreb",
                    },{
                        kljuc: "11",
                        ime: "Novak Đoković",
                        sport: "Tenis",
                        placeno: "1",
                        nacin: "individualni",
                        kratkiOpis:"Srbijanski je profesionalni tenisač, trenutno je prvi na ATP ljestvici, te jedan od najboljih tenisača današnjice.",
                        duziOpis:"Đoković je počeo trenirati već u četvrtoj godini, a svoj premijerni nastup na ATP turnirima imao je u Umagu, 19. srpnja 2004. godine gdje je u prvom kolu izgubio od Talijana Filippa Volandrija. Svoju prvu pobjedu na ATP turniru ostvario je u Bukureštu iste godine, kada je bio bolji od Francuza Arnauda Clementa. Već sljedeće godine po prvi puta nastupa i na jednom Grand Slam turniru. Bilo je to na Australian Openu, gdje je glatko izgubio od tadašnjeg četvrtog igrača svijeta, Rusa Marata Safina sa 6:0, 6:2, 6:1.",
                        lokacija:"Split",
                    },{
                        kljuc: "12",
                        ime: "Shaquille O'Neal",
                        sport: "Košarka",
                        placeno: "0",
                        nacin: "grupni",
                        kratkiOpis:"Umirovljeni američki profesionalni košarkaš. Igrao je na poziciji centra.",
                        duziOpis:"Izabran je kao prvi izbor NBA drafta 1992. od strane Orlando Magica. Prije odlaska u Orlando, O'Neal je proveo nekoliko dana u Los Angelesu u društvu Magicom Johnsonom. U svojoj rookie sezoni O'Neal je pomogao momčadi da ostvari 20 pobjeda više nego prethodne sezone te je prosječno postizao 23,9 poena i 13,10 skokova. Na kraju sezone, O'Neal je dobio nagradu za novaka godine",
                        lokacija:"Zagreb",
                        
                    
                    
                       
                        },
    ]